`line 2 "counter.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\SV

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
`line 0 "counter.sv" 1
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For $cnt.
logic [15:0] L0_cnt_a0,
             L0_cnt_a1;

// For $reset.
logic L0_reset_a0;



   // Staging of $cnt.
   always_ff @(posedge clk) L0_cnt_a1[15:0] <= L0_cnt_a0[15:0];


// ---------- Generated Code Ends ----------
`line 6 "counter.tlv" 2
//_\TLV
   assign L0_reset_a0 = reset;
   
   //$num[31:0] = $reset ? 1 : (>>1$num + >>2$num);
   
   assign L0_cnt_a0[15:0] = L0_reset_a0 ? 20 : (L0_cnt_a1 + 1);
   
   assign passed = cyc_cnt > 40;
   assign failed = 1'b0;
//_\SV
   endmodule



// Undefine macros defined by SandPiper.
`undef BOGUS_USE
