`line 2 "combo_calculator.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\SV

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
`line 0 "combo_calculator.sv" 1
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For $diff.
logic [31:0] L0_diff_a0;

// For $op.
logic L0_op_a0;

// For $out.
logic [31:0] L0_out_a0;

// For $prod.
logic [31:0] L0_prod_a0;

// For $quot.
logic [31:0] L0_quot_a0;

// For $random1.
logic [3:0] L0_random1_a0;

// For $random2.
logic [3:0] L0_random2_a0;

// For $reset.
logic L0_reset_a0;

// For $sum.
logic [31:0] L0_sum_a0;

// For $val1.
logic [31:0] L0_val1_a0;

// For $val2.
logic [31:0] L0_val2_a0;



   // Staging of signal $op, which had no assignment.
   assign L0_op_a0 = 'x;

   // Staging of signal $random1, which had no assignment.
   assign L0_random1_a0[3:0] = 'x;

   // Staging of signal $random2, which had no assignment.
   assign L0_random2_a0[3:0] = 'x;


// ---------- Generated Code Ends ----------
`line 6 "combo_calculator.tlv" 2
//_\TLV
   assign L0_reset_a0 = reset;
   
   assign L0_val1_a0[31:0] = {30'b0, L0_random1_a0[3:0]};
   assign L0_val2_a0[31:0] = {30'b0, L0_random2_a0[3:0]};
   assign L0_sum_a0[31:0] = L0_val1_a0[31:0] + L0_val2_a0[31:0];
   assign L0_diff_a0[31:0] = L0_val1_a0 - L0_val2_a0;
   assign L0_prod_a0[31:0] = L0_val1_a0 * L0_val2_a0;
   assign L0_quot_a0[31:0] = L0_val1_a0 / L0_val2_a0;
   
   assign L0_out_a0[31:0] =
      L0_op_a0 == 2'b00 ? L0_sum_a0 :
      L0_op_a0 == 2'b01 ? L0_diff_a0 :
      L0_op_a0 == 2'b10 ? L0_prod_a0 :
                     L0_quot_a0;
   
   assign passed = cyc_cnt > 40;
   assign failed = 1'b0;
//_\SV
   endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
